config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'site#index'

  namespace :site do
    get :portfolio
    get :project
    get :about
    get :contacts
    get :blog
    get :blog_more
    get :services
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def portfolio
  end

  def project
  end

  def about
  end

  def contacts
  end

  def blog
  end

  def blog_more
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def js_void
    'javascript:void(0);'
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru-Ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Arthouse" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_pack_tag    "application" %>
    <%= javascript_pack_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render partial: 'site/header'  %>
    <%= yield %>
    <%= render partial: 'site/footer'  %>

    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag    "vue-app" %>
  </body>
</html>

app/views/site/_footer.slim
footer.b-footer
  .__white-bg
    .b-we-are-on-instagram.grid-container
      .grid-x.align-center
        .medium-8.large-4.cell
          h3.__d
            span Мы в instagram

      .grid-x.align-center
        .medium-9.cell.b-instagram-photos
          #v-instagram

    .b-search.grid-container
      .grid-x.align-center
        .medium-3.cell
          .cell
            .b-logo
              = image_tag 'logo-bottom_249x46.png', width: 249, height: 46
          .cell
            .b-results-box
              i.icon.search

  .grid-container
    .grid-x.margin-x
      .small-11.small-offset-1.medium-offset-0.medium-2.cell
        ul.no-bullet
          li
            a href="#{js_void}" О студии
          li
            = active_link_to 'История', '/'
          li
            a href="#{js_void}" Команда
          li
            a href="#{js_void}" Блог
          li
            a href="#{js_void}" Акции
          li
            a href="#{js_void}" Вакансии
      .small-11.small-offset-1.medium-offset-0.medium-2.cell
        ul.no-bullet
          li
            a href="#{js_void}" Услуги
          li
            a href="#{js_void}" Прайс
          li
            a href="#{js_void}" Дизайн-проекты
          li
            a href="#{js_void}"
              ' Ремонты
              br
              | и отделка
      .small-11.small-offset-1.medium-offset-0.medium-2.cell
        ul.no-bullet
          li
            a href="#{js_void}" Проекты
          li
            a href="#{js_void}" Жилые
          li
            a href="#{js_void}" Коммерческие
      .small-11.small-offset-1.medium-offset-0.medium-2.cell
        ul.no-bullet
          li
            a href="#{js_void}" Контакты
          li
            a href="#{js_void}" Реквизиты
          li
            a href="#{js_void}" Партнёрам

      .small-offset-1.small-11.medium-4.medium-offset-0.cell
        .b-contacts
          .address
            i.icon.home
            | Благовещенск, пер. Ромненский, 14
          .phones
            i.icon.phone
            | +7 (4162) 771-772  /  +7 (4162) 771-773
          .instagram
            i.icon.instagram
            | Art_house_amur

  .__grey-bg
    .grid-container
      .grid-x.align-center
        .cell.b-copy
          | ООО «АРТHOUSE»
        .small-1.cell
          #v-to-top

/ Modal windows
#modal-order.reveal data-close-on-click="true" data-reveal=""
  .b-form
    form
      input type="text" placeholder="Ваше имя*"
      input type="text" placeholder="Ваш телефон*"
      input type="text" placeholder="Ваша почта*"
      .input-row
        input#agreed type="checkbox" value="0"
        label for="agreed" Соглашаюсь с правилами обработки персональных данных
      div.__d
        .wrap
          input type="submit" value="заказать"

  button.close-button aria-label=("Close reveal") data-close="" type="button"
    span aria-hidden="true"  &times;

app/views/site/_header.slim
header.b-header
  .b-contacts.grid-container
    .grid-x.grid-margin-x
      .medium-4.cell.hide-for-small-only
        i.icon.home
        | Благовещенск, пер. Ромненский, 14
      .small-10.medium-4.cell.text-center
        .phones
          i.icon.phone
          a href="tel:+74162771772" +7 (4162) 771-772
          span
            | /
          a href="tel:+74162771773" +7 (4162) 771-773
      .small-3.cell.hide-for-small-only
        a href="#{js_void}"
          i.icon.instagram
          | Art_house_amur

  .b-main-nav
    .grid-container
      .grid-x.grid-margin-x
        .small-8.small-offset-3.medium-3.medium-offset-0.cell
          .b-logo
            = link_to root_path do
              = image_tag 'logo_179x46.png', width: 179, heught: 46
        .small-12.medium-8.cell
          #v-mobile-nav
            a.mobile-nav.show-for-small-only href="#{js_void}" @click="toggleNavigation"

          nav#main-nav.b-nav.hide-for-small-only
            ul.no-bullet
              li
                = active_link_to 'Главная', root_path, active: :exclusive
              li
                = active_link_to 'Портфолио', site_portfolio_path
              li
                = active_link_to 'О нас', '/site/about'
              li
                = active_link_to 'Услуги', '/site/services'
              li
                = active_link_to 'Блог', '/site/blog'
              li
                = active_link_to 'Контакты', '/site/contacts'

        .small-4.medium-2.cell
          a.catalog-button href="#"

app/views/site/about.slim
#l-about-page
  .b-gradient-bg.__right
    .grid-container.__no-padding-right
      .grid-x
        .small-4.medium-6.cell.b-first-info
          h1
            | АРТHOUSE
            span.sub Это МЫ!

          h4.name.show-for-medium.medium-offset-2.b-leading-letter
            .__letter И
            .id
              span.name Ирина
              span.surname.__blue Кугай

          .grid-x.align-center.show-for-medium.b-total-info
            .medium-6.cell
              p
                | Если слова «атмосфера дома» и «уникальность идеи» для вас не пустой звук! Если дизайн интерьера в вашем понимании это не просто «бежевые обои» и ламинат! Если вас не удовлетворяет привычный всем набор стандартных вещей из строительных супермаркетов! Если вы тот, кто сам строит свой мир и решает каким он будет, обращайтесь к нам! Мы сделаем ваш дом неповторимым.

        .small-12.medium-6.cell.b-big-photo-cell
          = image_tag 'team/lead.jpg'

  .b-gradient-bg.__left
    .grid-container.b-team-slider.__no-padding-right
      #v-team-slider

  .grid-container
    .grid-x.b-why-us
      .medium-offset-1.medium-1.cell
        h2
          span.__large О
          span.__blue Нас
      .medium-9.cell.b-info
        .grid-x
          .cell
            h3 Почему мы...?
          .cell.b-text
            p
              | Компаний, предлагающих свои услуги в сфере ремонта и дизайна помещений, - сотни. Компаний, готовых предложить вам яркие и интересные проекты, - десятки. АРТHOUSE…не из их числа. АРТHOUSE - уникален. Мы не обещаем. Мы - проектируем и воплощаем. Мы создаем качественные, до деталей выверенные проекты. Работая честно и открыто, мы несем полную ответственность за ваш интерьер. Интерьер с запоминающейся внешностью и комфортным наполнением.
          .cell.b-video
            iframe width="100%" height="100%" src="https://www.youtube.com/embed/n_3kmvwL_9Q" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="true"

    .grid-x.b-achievements
      .medium-offset-1.medium-10.cell.b-i-understand
        ' «ВОТ
        span.__blue ЭТО Я ПОНИМАЮ!»
      .medium-offset-1.medium-10.cell
        .grid-x.medium-up-3.b-iconic
          .cell
            i.icon.light.green
            p
              | <span class="__text-up">Мы молоды и очень <br>амбициозны.</span> <span>И</span> уже <br> сейчас за плечами <br> нашего коллектива <br>впечатляющий <br> перечень <br> <span class="__text-up">реализованных <br> проектов</span>
          .cell
            i.icon.clipboard.green
            p
              | <span class="__text-up">С начала и до</span> <br> окончания реализации <br> проекта наша <br> компания <br> осуществляет полный  <br> <span class="__text-up">авторский надзор <br> над ним</span>
          .cell
            i.icon.connected.green
            p
              | <span class="__text-up">Большая часть</span> <br> наших заказчиков <br> обращаются к нам по <br> рекомендации. <br> Друзьям <br> <span class="__text-up">плохого не <br> посоветуют</span>
          .cell
            i.icon.paint-cube.green
            p
              | <span class="__text-up">Мы сотрудничаем</span> <br> только с надежными <br> производителями и <br> <span class="__text-up">поставщиками</span>
          .cell
            i.icon.trophy.green
            p
              | <span class="__text-up">Мы берем на себя</span> <br> финансовую <br> ответственность за <br> соблюдение сроков <br><span class="__text-up">выполнения работ</span>
          .cell
            i.icon.warning.green
            p
              | <span class="__text-up">Мы честны</span><br>
                со своими партнерами <br> и всегда уверены в их <br>
                <span class="__text-up">надежности</span>

        .grid-x.align-center
          .small-8.medium-8.large-offset-4.large-8.cell
            .b-we-know
              p
                | И да! <br>
                  <span class="__blue">Мы знаем</span>, где выгодно покупать!

  .__black-bg
    .grid-container
      .grid-x
        .small-12.cell.b-certificates
          #v-certificates-slider

  .__grey-bg
    .grid-container.b-mentions
      .grid-x
        .medium-12.cell
          h2.medium-text-right
            | Слова
            span.sub Наших Клиентов
      .grid-x
        .small-12.medium-offset-1.medium-10
          #v-mentions-slider

app/views/site/blog.slim
#l-blog-page
  .__gradient-bg
    .grid-container.__no-padding
      .grid-x.b-blog-article
        .medium-7.cell.b-image-cell
          = image_tag 'blog/blog-image-1.jpg'
          h3
            | Dизайн
            span.sub Студия
        .medium-5.cell.b-description-cell.__black-bg
          .b-title
            .super Скидка 10%
            h2.text
              | На некоторые
              span.__spacing коллекции
            .sub дизайнерских обоев
          .b-description
            .annotate 2017-02-16 Art Менеджер
            .text
              p
                | Еще не отгремели новогодние праздники, а мы Вам уже предлагаем задуматься о весне. Потому что до 31.01.17 мы дарим скидку 10% на некоторые артикулы весенних, романтических и очень атмосферных коллекций обоев и панно.
            a.like href="#{js_void}"

          .more.right.__d
            = link_to site_blog_more_path, class: 'button' do
              .wrap Читать далее

      .grid-x.b-blog-article
        .medium-5.cell.b-description-cell.__white-bg
          .b-title
            .super Текстильные
            h2.text
              | Обои
            .sub Armani Casa
          .b-description
            .annotate 2017-01-18 Менеджер
            .text
              p
                | Обои — наиболее распростра-
                  ненный отделочный материал в современном мире, редко какой интерьер обходится без них. Сейчас существует очень много видов обоев, начиная от обычных бумажных и заканчи-
                  вая текстильными обоями.
            a.like href="#{js_void}"

          .more.left.__d
            = link_to site_blog_more_path, class: 'button' do
              .wrap Читать далее

        .medium-7.cell.b-image-cell
          = image_tag 'blog/blog-image-2.jpg'
          h3
            | Dизайн
            span.sub Студия

      .grid-x.b-blog-article
        .medium-7.cell.b-image-cell
          = image_tag 'blog/blog-image-3.jpg'
          h3
            | Dизайн
            span.sub Студия
        .medium-5.cell.b-description-cell.__white-bg
          .b-title
            .super Скидка 10%
            h2.text
              | На некоторые
              span.__spacing коллекции
            .sub дизайнерских обоев
          .b-description
            .annotate 2017-02-16 Art Менеджер
            .text
              p
                | Еще не отгремели новогодние праздники, а мы Вам уже предлагаем задуматься о весне. Потому что до 31.01.17 мы дарим скидку 10% на некоторые артикулы весенних, романтических и очень атмосферных коллекций обоев и панно.
            a.like href="#{js_void}"

          .more.right.__d
            = link_to site_blog_more_path, class: 'button' do
              .wrap Читать далее

      // part 2
      .grid-x.b-blog-article
        .medium-5.cell.b-description-cell.__white-bg
          .b-title
            .super Скидка 10%
            h2.text
              | На некоторые
              span.__spacing коллекции
            .sub дизайнерских обоев
          .b-description
            .annotate 2017-02-16 Art Менеджер
            .text
              p
                | Еще не отгремели новогодние праздники, а мы Вам уже предлагаем задуматься о весне. Потому что до 31.01.17 мы дарим скидку 10% на некоторые артикулы весенних, романтических и очень атмосферных коллекций обоев и панно.
            a.like href="#{js_void}"

          .more.left.__d
            = link_to site_blog_more_path, class: 'button' do
              .wrap Читать далее

        .medium-7.cell.b-image-cell
          = image_tag 'blog/blog-image-1.jpg'
          h3
            | Dизайн
            span.sub Студия

      .grid-x.b-blog-article
        .medium-7.cell.b-image-cell
          = image_tag 'blog/blog-image-2.jpg'
          h3
            | Dизайн
            span.sub Студия

        .medium-5.cell.b-description-cell.__black-bg
          .b-title
            .super Текстильные
            h2.text
              | Обои
            .sub Armani Casa
          .b-description
            .annotate 2017-01-18 Менеджер
            .text
              p
                | Обои — наиболее распростра-
                  ненный отделочный материал в современном мире, редко какой интерьер обходится без них. Сейчас существует очень много видов обоев, начиная от обычных бумажных и заканчи-
                  вая текстильными обоями.
            a.like href="#{js_void}"

          .more.right.__d
            = link_to site_blog_more_path, class: 'button' do
              .wrap Читать далее

      .grid-x.b-blog-article
        .medium-5.cell.b-description-cell.__white-bg
          .b-title
            .super Скидка 10%
            h2.text
              | На некоторые
              span.__spacing коллекции
            .sub дизайнерских обоев
          .b-description
            .annotate 2017-02-16 Art Менеджер
            .text
              p
                | Еще не отгремели новогодние праздники, а мы Вам уже предлагаем задуматься о весне. Потому что до 31.01.17 мы дарим скидку 10% на некоторые артикулы весенних, романтических и очень атмосферных коллекций обоев и панно.
            a.like href="#{js_void}"

          .more.left.__d
            = link_to site_blog_more_path, class: 'button' do
              .wrap Читать далее

        .medium-7.cell.b-image-cell
          = image_tag 'blog/blog-image-3.jpg'
          h3
            | Dизайн
            span.sub Студия

  .__white-bg
    .grid-container.__no-padding
      .grid-x.b-paginate.__white-bg
        .small-12.cell
          ul.no-bullet
            li.current
              a href="#{js_void}" 1
            li
              a href="#{js_void}" 2
            li
              a href="#{js_void}" 3
            li
              a href="#{js_void}" 4
            li
              a href="#{js_void}" 5
            li
              a href="#{js_void}" 6
            li
              a href="#{js_void}" 7
            li
              a href="#{js_void}" 8
            li
              a href="#{js_void}" 9
            li
              a href="#{js_void}" 10

.__black-pattern
  .grid-container.__no-padding
    .grid-x.b-subscribe-pls
      .medium-offset-3.medium-7.cell
        h4
          | АРТHOUSE
          span.sub Галерея ИНТЕРЬЕРОВ
      .medium-offset-1.medium-4.cell
        .cell
          p
            span.__blue 897
            | пользователей еженедельно
              получают от нас по одному письму
              со скидками,
              обзорами ремонтов,
              новостями мира дизайна.
        .cell
          .b-subscribe-now
            | Подпишись
            span.__blue И ТЫ!

      .medium-5.cell
        .b-form
          form
            input type="text" placeholder="Ваше имя*"
            input type="text" placeholder="Ваш EMAIL*"
            div.__d
              .wrap
                input type="submit" value="Подписаться"

          .b-motivation
            i.lock.small.aqua.icon
            span Безопасная подписка

app/views/site/blog_more.slim
#l-blog-more-page
  .__black-bg
    .grid-container.__no-padding
      .grid-x.b-img-composition
        .small-12.medium-7.cell
          = image_tag 'blog/big-inner-image.jpg', class: 'big'
        .small-12.medium-5.cell
          .grid-x
            .small-6.medium-12.cell
              = image_tag 'blog/small-inner-image-1.jpg'
            .small-6.medium-12.cell
              = image_tag 'blog/small-inner-image-2.jpg'

  .__white-bg
    article.grid-container
      .grid-x.
        .small-10.small-offset-1
          h1
            span.up Целостный
            span.__blue Интерьер
            span.sub — это КАК?

          .b-text
            p
              | Бывает такое, что входишь в отремонтированную квартиру и… вроде красиво, чисто, но чего-то не хватает?
            p
              | Давайте разберемся, как создать целостный интерьер, который будет производить впечатление законченности.
            p
              | Основа интерьера – двери, стены и пол. Это та база, на которой уж точно не стоит экономить. Подобрав качественные двери и полы, выровняв стены, вы обеспечите себя  своеобразным «тылом»  на долгие годы. Можно менять цвет стен, мебель и аксессуары без ущерба для будней домочадцев, однако, чтобы сменить двери и полы, придется освобождать жилое пространство на весь период ремонта.
            p
              | Выбор материалов – тема, достойная отдельной статьи. Из актуального в мире полов и дверей: рекомендуем обратить внимание на изделия с использованием Кортекса. Это инновационный материал, который имитирует натуральную доску и, при этом, обладает высокой влагостойкостью, а значит практичность и эстетика интерьера обеспечены на долгие годы. Этот материал использует в производстве фабрика полов, дверей и интерьеров Sofia (Софья). Продукция этой фабрики с недавнего времени представлена в монобрендовом фирменном салоне в Благовещенске по адресу ул. Ленина 179.
            p
              | Что касается стен – вариантов отделки превеликое множество. Главный фактор, их идеальная геометрия. Тогда любая отделка будет выглядеть достойно. Обои лягут ровно и без стыков, не будет перерасхода краски, как это бывает в случае кривых стен. Огромный выбор обоев в нашем каталоге продукции. Что касается декоративных покрытий, наш бесспорный фаворит – декоративные итальянские краски Valpaint

  .__black-bg
    .grid-container.__no-padding
      .grid-x.b-img-composition
        .small-12.medium-5.cell
          .grid-x
            .small-6.medium-12.cell
              = image_tag 'blog/small-inner-image-1.jpg'
            .small-6.medium-12.cell
              = image_tag 'blog/small-inner-image-2.jpg'
        .small-12.medium-7.cell
          = image_tag 'blog/big-inner-image.jpg', class: 'big'

  .__grey-bg
    .grid-container
      .grid-x
        .small-10.small-offset-1
          .b-text
            p
              |  Бывает такое, что входишь в отремонтированную квартиру и… вроде красиво, чисто, но чего-то не хватает?
            p
              | Давайте разберемся, как создать целостный интерьер, который будет производить впечатление законченности.
            p
              | Основа интерьера – двери, стены и пол. Это та база, на которой уж точно не стоит экономить. Подобрав качественные двери и полы, выровняв стены, вы обеспечите себя  своеобразным «тылом»  на долгие годы. Можно менять цвет стен, мебель и аксессуары без ущерба для будней домочадцев, однако, чтобы сменить двери и полы, придется освобождать жилое пространство на весь период ремонта.
            p
              | Выбор материалов – тема, достойная отдельной статьи. Из актуального в мире полов и дверей: рекомендуем обратить внимание на изделия с использованием Кортекса. Это инновационный материал, который имитирует натуральную доску и, при этом, обладает высокой влагостойкостью, а значит практичность и эстетика интерьера обеспечены на долгие годы. Этот материал использует в производстве фабрика полов, дверей и интерьеров Sofia (Софья). Продукция этой фабрики с недавнего времени представлена в монобрендовом фирменном салоне в Благовещенске по адресу ул. Ленина 179.

            p Больше красивых интерьеров в нашем портфолио работ

            p
              | А обратиться за помощью
                профессиональных дизайнеров можно по телефону 771-772,
                пер. Ромненский 14, галерея интерьеров АРТHOUSE.

      .grid-x.b-actions
        .small-8.small-offset-4.medium-5.medium-offset-7.shrink.cell
          = link_to '< Вернуться назад',site_portfolio_path, class: 'b-go-back'
          a.add.b-like href="#{js_void}"

      .grid-x.small-up-2.medium-up-4.b-photos
        .cell
          = image_tag 'blog/article-image-1.jpg'
        .cell
          = image_tag 'blog/article-image-2.jpg'
        .cell
          = image_tag 'blog/article-image-3.jpg'
        .cell
          = image_tag 'blog/article-image-4.jpg'

  .__black-pattern
    .grid-container.__no-padding
      .grid-x.b-subscribe-pls
        .medium-offset-3.medium-7.cell
          h4
            | АРТHOUSE
            span.sub Галерея ИНТЕРЬЕРОВ
        .medium-offset-1.medium-4.cell
          .cell
            p
              span.__blue 897
              | пользователей еженедельно
                получают от нас по одному письму
                со скидками,
                обзорами ремонтов,
                новостями мира дизайна.
          .cell
            .b-subscribe-now
              | Подпишись
              span.__blue И ТЫ!

        .medium-5.cell
          .b-form
            form
              input type="text" placeholder="Ваше имя*"
              input type="text" placeholder="Ваш EMAIL*"
              div.__d
                .wrap
                  input type="submit" value="Подписаться"

            .b-motivation
              i.lock.small.aqua.icon
              span Безопасная подписка

app/views/site/portfolio.slim
#l-portfolio-page
  .__grey-bg
    .grid-container.__no-padding
      .b-top.grid-x
        .small-12.cell.small-text-center.large-text-right
          section
            h1 Портфолио
            nav
              ul.no-bullet.text-center.medium-text-left
                li
                  a.active href="#{js_void}" Проекты
                li
                  a href="#{js_void}" Реализация

    .grid-container.__no-padding
      .b-portfolio-items
        .grid-x
          .medium-3.cell
            .card
              .card-section
                = image_tag 'portfolio/size-1.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
            .card
              .card-section
                = image_tag 'portfolio/size-4.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
          .medium-3.cell
            .card
              .card-section
                = image_tag 'portfolio/size-2.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
            .card
              .card-section
                = image_tag 'portfolio/size-5.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
          .medium-6.cell
            .card
              .card-section
                = image_tag 'portfolio/size-3.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:

        // Reverse ordering
        .grid-x.__reverse
          .medium-6.cell
            .card
              .card-section
                = image_tag 'portfolio/size-3.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
          .medium-3.cell
            .card
              .card-section
                = image_tag 'portfolio/size-2.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
            .card
              .card-section
                = image_tag 'portfolio/size-5.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
          .medium-3.cell
            .card
              .card-section
                = image_tag 'portfolio/size-1.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:
            .card
              .card-section
                = image_tag 'portfolio/size-4.jpg'
                = link_to site_project_path, class: 'info' do
                  .title
                    <span> Дизайн </span>
                    | Интерьера КВАРТИРЫ
                  .more.__d
                    .wrap Подробнее
                  .attributes
                    .style Стиль:
                    .budget Бюджет:

  .__black-bg
    .grid-container.b-order-buttons
      .grid-x.align-center
        .small-8.medium-offset-1.medium-3.cell
          a.order-design href="#{js_void}" data-toggle="modal-order"
        .small-8.medium-offset-1.medium-3.cell
          a.order-repair href="#{js_void}" data-toggle="modal-order"
        .small-8.medium-offset-1.medium-3.cell
          a.order-materials href="#{js_void}"

app/views/site/project.slim
#l-project-page
  .b-slider
    #v-main-slider
  .b-alt-slider
    #v-works-slider

  .__black-bg
    .grid-container.b-about-design
      .grid-x
        .medium-4.cell
          h1
            span.up 118,7 м.кв.
            span.__blue Дизайн
            span.sub Интерьера КВАРТИРЫ

          .b-attributes
            .style Стиль:
            .budget Бюджет:

        .medium-8.cell
          .b-project-info
            p
              | Современный дом для современных людей, которые сочетают в своей жизни последние блага цивилизации и любовь к непорочной красоте природы.
            p
              | Пространство, в котором нет ничего лишнего, где все необходимое для комфортной жизни всегда под рукой. Где органичность пейзажей за окном продолжается и в стенах каждой комнаты…
            p
              | Нouse of sand. Современный дом для современных людей, которые сочетают в своей жизни последние блага цивилизации и любовь к непорочной красоте природы. Пространство, в котором нет ничего лишнего, где все необходимое для комфортной жизни под рукой.

    .grid-x
      .medium-7.medium-offset-5.large-offset-6.large-5
        .b-go-back
          = link_to '< Вернуться к портфолио', site_portfolio_path
        .b-order.__black-bg
          .more.right.__d
            = link_to js_void, class: 'button' do
              .wrap Хочу такой же